### ISSUE TITLE
Data Generation

### ISSUE THREAD

**Issue by twtygqyy** [mks0601/Photo-Realistic-Single-Image-Super-Resolution-Using-a-Generative-Adversarial-Network#2]
Hi, I have several questions about the code you used for data generation.
It seems that you use 41x41 with only intensity channel for creating both input images and labels, while according to the paper, I think the input should be RGB 24x24 patches and the output should be RGB 96x96 patches. Did I make some mistakes for understanding your code or the paper? I appreciate if you can provide me some suggestions.

**Comment by mks0601** [comment]
In train.lua, the input tensor has a size of (curBatchDim, inputDim, inputSz, inputSz).
In etc.lua, inputDim = 3, inputSz = 96/4 = 24

**Comment by twtygqyy** [comment]
@mks0601 Thanks for the reply. I thought you used the matlab code [https://github.com/mks0601/Photo-Realistic-Single-Image-Super-Resolution-Using-a-Generative-Adversarial-Network/blob/SRResNet/dataGen/generate_train.m](url) in your dataGen folder for generation

**Comment by mks0601** [comment]
I in this project, i do not use that script. Only use generate_test.m
I`ll update my repo. Thanks
